---
apiVersion: v1
kind: Template
metadata:
  name: workshop
  annotations:
    openshift.io/display-name: "Workshop (Ephemeral)"
    description: "An example of a ToDo List Application written in Java."
    iconClass: "icon-jboss"
    tags: "kermit-tutorial,jboss,kermit,java"
labels:
  template: workshop
objects:
# +++++++++++++++++++++++++++
# ++++++ LAYER 1 IMAGES +++++
# +++++++++++++++++++++++++++
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      description: "Resulting Docker Image after the buit of my application frontend."
  spec:
    tags:
      -
        tag: latest
# +++++++++++++++++++++++++++
# ++++++ LAYER 2 BUILDS +++++
# +++++++++++++++++++++++++++
- apiVersion: v1
  kind: BuildConfig
  metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
        annotations:
          description: "Defines how to build the application"
  spec:
    triggers:
      -
        type: ImageChange
        imageChange: {}
      -
        type: ConfigChange
      -
        type: GitHub
        github:
          secret: "${WEBHOOK_SECRET}"
      -
        type: Generic
        generic:
          secret: "${WEBHOOK_SECRET}"
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_CONTEXT}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: "jboss-webserver30-tomcat7-openshift:latest"
        env: {}
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
# +++++++++++++++++++++++++++
# +++ LAYER 3 DEPLOYMENTS +++
# +++++++++++++++++++++++++++
# ///////////////////////////
# /// FRONTEND DEPLOYMENT ///
# ///////////////////////////
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
    annotations:
      description: "Defines how to deploy the application server"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
    triggers:
      -
        type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            name: ${APPLICATION_NAME}:latest
      -
        type: ConfigChange
    replicas: 1
    test: false
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          deploymentConfig: ${APPLICATION_NAME}
      spec:
        containers:
          -
            name: "${APPLICATION_NAME}"
            image: "${APPLICATION_NAME}"
            ports:
              -
                name: "port-http"
                containerPort: 8080
                protocol: TCP
              -
                name: "port-https"
                containerPort: 8443
                protocol: TCP
            resources: {}
            terminationMessagePath: "/dev/termination-log"
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: false
        restartPolicy: "Always"
        terminationGracePeriodSeconds: 30
        dnsPolicy: "ClusterFirst"

# +++++++++++++++++++++++++++++++++
# ++++++ LAYER 4 ABSTRACTIONS +++++
# +++++++++++++++++++++++++++++++++
# ////////////////////////
# /// FRONTEND SERVICE ///
# ////////////////////////
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APPLICATION_NAME}-svc"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      description: "Exposes and load balances the application frontend pods."
  spec:
    ports:
      -
        name: "port-http"
        protocol: TCP
        port: 8080
        targetPort: 8080
      -
        name: "port-https"
        protocol: TCP
        port: 8443
        targetPort: 8443
    selector:
      deploymentConfig: ${APPLICATION_NAME}
# ----------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------
# ////////////////////////
# /// FRONTEND ROUTE /////
# ////////////////////////
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
      network: ${PUBLIC_NETWORK}
    annotations:
      description: "The route exposes the frontend service at a hostname."
  spec:
    host: "${APPLICATION_HOSTNAME}"
    to:
      kind: Service
      name: ${APPLICATION_NAME}-svc
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow
# ----------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------
# ////////////////////
# /// PARAMETERS /////
# ////////////////////
parameters:
  - name: "APPLICATION_NAME"
    displayName: "Application name"
    description: "The name assigned to all of the objects defined in this template."
    required: true
    value: "workshop"
  - name: "APPLICATION_HOSTNAME"
    displayName: "Application hostname"
    description: "The hostname for exposing your application on the Internal Network (*.kermit.itn.intraorange) or on the Internet (*.kmt.orange.com)."
  - name: "PUBLIC_NETWORK"
    displayName: "If your application will be exposed on the Internet (HOSTNAME = *.kmt.orange.com) you need to setup this flag with the value: public"
    description: "The name assigned to all of the objects defined in this template."
  - name: "SOURCE_REPOSITORY_URL"
    displayName: "Git Repository URL"
    description: "The URL of the repository with your application source code."
    required: true
    value: "https://github.com/orangekmt/workshop-ephemeral.git"
  - name: "SOURCE_REPOSITORY_REF"
    displayName: "Git Repository Reference"
    description: "The branch/tag/ref inside the repository where your application source code resides."
    value: "master"
  - name: "SOURCE_REPOSITORY_CONTEXT"
    displayName: "Git Repository Context Directory"
    description: "The location inside the repository where your application source code resides."
  - name: "WEBHOOK_SECRET"
    displayName: "Git Webhook Secret"
    description: "A secret string used to configure the Git webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"